[tool.pytest.ini_options]
pythonpath = ["."]
env = [
    "WITHGUI=0" # Skip GUI logic when unit testing
]

[tool.coverage.run]
omit = [
    "src/config.py",
    "*GUI.py",
    "*__init__.py",
    "tests/*"
]


